__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
protected_areas_in_europe:
    runtime: 239
    memory: 64000
settlements:
    cores: 4
    runtime: 240
shared_coast:
    cores: 4
    runtime: 60
tech_slope_thresholds:
    cores: 4
    runtime: 60
slope_thresholds_warped_to_land_cover:
    cores: 4
    runtime: 60
eez_eligibility:
    cores: 4
sensitivities:
    cores: 4
capacityfactor_timeseries:
    memory: 128000
    runtime: 180
time_average_capacityfactor_map:
    memory: 32000
national_boundaries:
    runtime: 60
administrative_borders:
    runtime: 240
