
data-sources:
    sub-national-shapes: data/custom-sub-national-shapes.geojson
layers:
    custom-sub-national:
        # These shapes are based on the E-Highways2050 shapes, which are aggregations of 2006 NUTS3 regions.
        # Where no subnational shapes are used for a country, NUTS/GADM is used.
        Austria: sub-national-shapes
        Belgium: nuts0
        Bulgaria: nuts0
        Croatia: nuts0
        Cyprus: nuts0
        Czech Republic: sub-national-shapes
        Denmark: sub-national-shapes
        Estonia: nuts0
        Finland: sub-national-shapes
        France: sub-national-shapes
        Germany: sub-national-shapes
        Greece: sub-national-shapes
        Hungary: nuts0
        Ireland: nuts0
        Italy: sub-national-shapes
        Latvia: nuts0
        Lithuania: nuts0
        Luxembourg: nuts0
        Netherlands: nuts0
        Poland: sub-national-shapes
        Portugal: sub-national-shapes
        Romania: sub-national-shapes
        Slovakia: nuts0
        Slovenia: nuts0
        Spain: sub-national-shapes
        Sweden: sub-national-shapes
        United Kingdom: sub-national-shapes
        Albania: gadm0
        Bosnia and Herzegovina: gadm0
        North Macedonia: gadm0
        Montenegro: gadm0
        Norway: sub-national-shapes
        Serbia: gadm0
        Switzerland: sub-national-shapes
        Iceland: nuts0
