snakemake:
    max-threads: 4
data-sources:
    load: https://data.open-power-system-data.org/time_series/2018-06-30/time_series_60min_stacked.csv
    nuts: https://ec.europa.eu/eurostat/cache/GISCO/distribution/v2/nuts/geojson/NUTS_RG_01M_{nuts_year}_4326.geojson
    lau: http://ec.europa.eu/eurostat/cache/GISCO/geodatafiles/COMM-01M-2013-SH.zip
    degurba: http://ec.europa.eu/eurostat/cache/GISCO/geodatafiles/DGURBA_2014_SH.zip
    land_cover: http://due.esrin.esa.int/files/Globcover2009_V2.3_Global_.zip
    protected_areas: https://www.protectedplanet.net/downloads/WDPA_Feb2019?type=shapefile
    cgiar_tile: http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/
    gmted_tile: https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/downloads/GMTED/Global_tiles_GMTED/075darcsec/mea/
    gadm: https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_{country_code}_gpkg.zip
    bathymetric: https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/grid_registered/georeferenced_tiff/ETOPO1_Bed_g_geotiff.zip
    pop: http://cidportal.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_GPW4_GLOBE_R2015A/GHS_POP_GPW42015_GLOBE_R2015A_54009_250/V1-0/GHS_POP_GPW42015_GLOBE_R2015A_54009_250_v1_0.zip
    settlement_data: data/esm-100m-2017/ESM_class{esm_class}_100m.tif
    eez_data: data/World_EEZ_v10_20180221/eez_v10.shp
    sonnendach_statistics: https://zenodo.org/record/4091033/files/roof-statistics.csv?download=1
    sonnendach_total_size: https://zenodo.org/record/4091033/files/total-rooftop-area-km2.txt?download=1
    sonnendach_total_yield: https://zenodo.org/record/4091033/files/total-yield-twh.txt?download=1
    raw-capacity-factors: data/capacityfactors/{technology}.nc
    slope: data/eudem_slop_3035_europe.tif
root-directory: . # point to the root directory if working directory is not root directory
crs: "EPSG:4326"
scope:
    countries:
        - "Austria"
        - "Belgium"
        - "Bulgaria"
        - "Croatia"
        - "Cyprus"
        - "Czech Republic"
        - "Denmark"
        - "Estonia"
        - "Finland"
        - "France"
        - "Germany"
        - "Greece"
        - "Hungary"
        - "Ireland"
        - "Italy"
        - "Latvia"
        - "Lithuania"
        - "Luxembourg"
        - "Netherlands"
        - "Poland"
        - "Portugal"
        - "Romania"
        - "Slovakia"
        - "Slovenia"
        - "Spain"
        - "Sweden"
        - "United Kingdom"
        - "Albania"
        - "Bosnia and Herzegovina"
        - "North Macedonia"
        - "Montenegro"
        - "Norway"
        - "Serbia"
        - "Switzerland"
        - "Iceland"
    bounds:
        x_min: -30 # in degrees east
        x_max: 37  # in degrees east
        y_min: 30  # in degrees north
        y_max: 75  # in degrees north
    exclusion_zones:
        atlantic_islands:
            x_min: -30 # in degrees east
            x_max: -10  # in degrees east
            y_min: 30  # in degrees north
            y_max: 41  # in degrees north

layers:
    continental:
        Austria: nuts0
        Belgium: nuts0
        Bulgaria: nuts0
        Croatia: nuts0
        Cyprus: nuts0
        Czech Republic: nuts0
        Denmark: nuts0
        Estonia: nuts0
        Finland: nuts0
        France: nuts0
        Germany: nuts0
        Greece: nuts0
        Hungary: nuts0
        Ireland: nuts0
        Italy: nuts0
        Latvia: nuts0
        Lithuania: nuts0
        Luxembourg: nuts0
        Netherlands: nuts0
        Poland: nuts0
        Portugal: nuts0
        Romania: nuts0
        Slovakia: nuts0
        Slovenia: nuts0
        Spain: nuts0
        Sweden: nuts0
        United Kingdom: nuts0
        Albania: gadm0
        Bosnia and Herzegovina: gadm0
        North Macedonia: gadm0
        Montenegro: gadm0
        Norway: nuts0
        Serbia: gadm0
        Switzerland: nuts0
        Iceland: nuts0
    national:
        Austria: nuts0
        Belgium: nuts0
        Bulgaria: nuts0
        Croatia: nuts0
        Cyprus: nuts0
        Czech Republic: nuts0
        Denmark: nuts0
        Estonia: nuts0
        Finland: nuts0
        France: nuts0
        Germany: nuts0
        Greece: nuts0
        Hungary: nuts0
        Ireland: nuts0
        Italy: nuts0
        Latvia: nuts0
        Lithuania: nuts0
        Luxembourg: nuts0
        Netherlands: nuts0
        Poland: nuts0
        Portugal: nuts0
        Romania: nuts0
        Slovakia: nuts0
        Slovenia: nuts0
        Spain: nuts0
        Sweden: nuts0
        United Kingdom: nuts0
        Albania: gadm0
        Bosnia and Herzegovina: gadm0
        North Macedonia: gadm0
        Montenegro: gadm0
        Norway: nuts0
        Serbia: gadm0
        Switzerland: nuts0
        Iceland: nuts0
    regional:
        # The link between NUTS and administrative units unfortunately is not obvious.
        # It's not documented anywhere -- at least I could not find any information.
        # Hence, I am using GADM here instead.
        # Validation source: https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country
        Austria: gadm1 # gadm1 and wiki match 9
        Belgium: gadm1 # match 3
        Bulgaria: gadm1 # match 28
        Croatia: gadm1 # match 21
        Cyprus: gadm1 # gadm1: 5 regions; wiki: 6 regions
        Czech Republic: gadm1 # match 14
        Denmark: gadm1 # match 5
        Estonia: gadm1 # gadm1 16 regions; wiki 15 regions
        Finland: gadm1 # gadm1 5 regions; wiki 19 regions
        France: gadm1 # match 13
        Germany: gadm1 # match 16
        Greece: gadm1 # gadm1 8 regions; wiki 13 (14) regions
        Hungary: gadm1 # match 20
        Ireland: gadm1 # match 26
        Italy: gadm1 # match 20
        Latvia: gadm1 # gadm1 5 regions; wiki 119 regions
        Lithuania: gadm1 # match 10
        Luxembourg: gadm2 # match 12
        Netherlands: gadm1 # gadm1 14 regions; wiki 12 regions
        Poland: gadm1 # match 16
        Portugal: gadm1 # match 18
        Romania: gadm1 # match 42
        Slovakia: gadm1 # match 8
        Slovenia: gadm1 # match 12
        Spain: gadm1 # match 17
        Sweden: gadm1 # match 21
        United Kingdom: gadm1 # match 4
        Albania: gadm1 # match 12
        Bosnia and Herzegovina: gadm1 # match 3
        North Macedonia: nuts3 # match 8 (statistical, non-administrative)
        Montenegro: gadm1 # match 21
        Norway: gadm1 # match 19
        Serbia: gadm1 # gadm1 25 regions; wiki 5 regions
        Switzerland: gadm1 # match 26
        Iceland: gadm1
    municipal:
        Austria: lau2
        Belgium: lau2
        Bulgaria: lau2
        Croatia: lau2
        Cyprus: lau2
        Czech Republic: lau2
        Denmark: lau2
        Estonia: lau2
        Finland: lau2
        France: lau2
        Germany: lau2
        Greece: lau2
        Hungary: lau2
        Ireland: lau2
        Italy: lau2
        Latvia: lau2
        Lithuania: lau2
        Luxembourg: lau2 # lau2 106, https://en.wikipedia.org/wiki/Communes_of_Luxembourg 102
        Netherlands: lau2
        Poland: lau2
        Portugal: lau2
        Romania: lau2
        Slovakia: lau2
        Slovenia: lau2
        Spain: lau2
        Sweden: lau2
        United Kingdom: lau2
        Albania: gadm3
        Bosnia and Herzegovina: gadm3
        North Macedonia: gadm1 # 85, instead of 1817 in LAU2; https://en.wikipedia.org/wiki/Municipalities_of_the_Republic_of_Macedonia
        Montenegro: gadm1 # same as regional
        Norway: lau2
        Serbia: lau2
        Switzerland: lau2
        Iceland: lau2
parameters:
    maximum-installable-power-density: # this is not the yield, but the density of installed power
        pv-on-tilted-roofs: 160 # [W/m^2] from (Gagnon:2016, Klauser:2016), i.e. 16% efficiency
        pv-on-flat-areas: 80 # [W/m^2] from (Gagnon:2016, Klauser:2016, Wirth:2017)
        onshore-wind: 8 # [W/m^2] from (European Environment Agency, 2009)
        offshore-wind: 15 # [W/m^2] from (European Environment Agency, 2009)
    availability:
        wind-onshore: 0.97 # [-] from (European Environment Agency, 2009)
        wind-offshore: 0.9 # [-] from (European Environment Agency, 2009)
    ninja: # change these with caution as the renewables.ninja simulations are not in the loop, see README
        resolution-grid: 50 # [km^2] corresponding to MERRA resolution
        pv-performance-ratio: 0.9
        hub-height:
            onshore: 105 # m, median hub height of V90/2000 in Europe between 2010 and 2018
            offshore: 87 # m, median hub height of SWT-3.6-107 in Europe between 2010 and 2018
        turbine:
            onshore: "vestas v90 2000" # most built between 2010 and 2018 in Europe
            offshore: "siemens swt 3.6 107" # most built between 2010 and 2018 in Europe
    max-slope:
        pv: 10 # [°] (AlGarni:2018)
        wind: 20 # [°] (McKenna:2014)
    max-slope-pixel-fraction-threshold: 0.9
    max-depth-offshore: -50
    max-building-share: 0.01 # Above, a pixel cannot be used for energy farms. Equals roughly 900m2
    max-urban-green-share: 0.01 # Above, a pixel cannot be used for energy farms. Equals roughly 900m2. Removes e.g. Berlin's Tempelhofer Feld.
    nuts-year: 2010  # Choice of NUTS data to use from [2006, 2010, 2013, 2016, 2021]
scenarios:
    technical-potential:
        use-protected-areas: True
        pv-on-farmland: True
        share-farmland-used: 1.0
        share-forest-used-for-wind: 1.0
        share-other-land-used: 1.0
        share-offshore-used: 1.0
        share-rooftops-used: 1.0
    technical-social-potential:
        use-protected-areas: False
        pv-on-farmland: False
        share-farmland-used: 0.1
        share-forest-used-for-wind: 0.1
        share-other-land-used: 0.1
        share-offshore-used: 0.1
        share-rooftops-used: 1.0
