$schema: "http://json-schema.org/draft-07/schema#"
description: Default configuration schema
properties:
    parameters:
        type: object
        properties:
            nuts-year:
                type: number
                enum: [2006, 2010, 2013, 2016, 2021]
                default: 2016
                description: Indicates the reference NUTS year
            wdpa-version:
                type: string
                descriptions: Indicates the latest Protected Planet WDPA year. Only the two latest datasets are available for download at any given time.