$schema: "http://json-schema.org/draft-07/schema#"
description: Default configuration schema
properties:
    parameters:
        type: object
        properties:
            nuts-year:
                type: number
                enum: [2006, 2010, 2013, 2016, 2021]
                description: Indicates the reference NUTS year
            max-slope-pixel-fraction-threshold:
                type: number
                minimum: 0
                maximum: 1
                description: Minimum fraction of each aggregated pixel that is not too steep for a technology to be deployed. 0.9 indicates that 90% of the pixel does not exceed a technology's slope threshold.
    crs:
        type: string
        enum: ["EPSG:4326"]
        description: Coordinate reference system to which all datasets are reprojected during preprocessing
    scope:
        type: object
        properties:
            countries:
                type: array
                items:
                    type: string
                    enum:
                        - "Austria"
                        - "Belgium"
                        - "Bulgaria"
                        - "Croatia"
                        - "Cyprus"
                        - "Czech Republic"
                        - "Denmark"
                        - "Estonia"
                        - "Finland"
                        - "France"
                        - "Germany"
                        - "Greece"
                        - "Hungary"
                        - "Ireland"
                        - "Italy"
                        - "Latvia"
                        - "Lithuania"
                        - "Luxembourg"
                        - "Netherlands"
                        - "Poland"
                        - "Portugal"
                        - "Romania"
                        - "Slovakia"
                        - "Slovenia"
                        - "Spain"
                        - "Sweden"
                        - "United Kingdom"
                        - "Albania"
                        - "Bosnia and Herzegovina"
                        - "North Macedonia"
                        - "Montenegro"
                        - "Norway"
                        - "Serbia"
                        - "Switzerland"
                        - "Iceland"
                    description: Countries to include in the model
            bounds:
                type: object
                properties:
                    x_min:
                        type: number
                        minimum: -180
                        maximum: 180
                        description: Minimum longitude, in degrees east
                    x_max:
                        type: number
                        minimum: -180
                        maximum: 180
                        description: Maximum longitude, in degrees east
                    y_min:
                        type: number
                        minimum: -90
                        maximum: 90
                        description: Minimum Latitude, in degrees north
                    y_max:
                        type: number
                        minimum: -90
                        maximum: 90
                        description: Maximum Latitude, in degrees north
                description: Total extent of system under study. Defaults to all of Europe
            exclusion_zones:
                type: object
                patternProperties:
                    ^.*$:
                        properties:
                            x_min:
                                type: number
                                minimum: -180
                                maximum: 180
                                description: Minimum longitude, in degrees east
                            x_max:
                                type: number
                                minimum: -180
                                maximum: 180
                                description: Maximum longitude, in degrees east
                            y_min:
                                type: number
                                minimum: -90
                                maximum: 90
                                description: Minimum Latitude, in degrees north
                            y_max:
                                type: number
                                minimum: -90
                                maximum: 90
                                description: Maximum Latitude, in degrees north
                description: Any number of bounding boxes defining exclusion zones, where spatial features within the total bounds are to be ignored.
    layers:
        type: object
        patternProperties:
            ^.*$:
                type: object
                properties:
                    ^.*$:  # ideally this would be 'oneof' the list of countries above (can this be done in a schema??)
                        type: string
                        enum:
                            - gadm0
                            - gadm1
                            - gadm2
                            - gadm3
                            - gadm4
                            - gadm5
                            - lau2
                            - nuts0
                            - nuts1
                            - nuts2
                            - nuts3

